# Site settings
title: CloudSurge 
description: CloudSurge Devops Consultancy 
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "https://cloudsurge.co.uk" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: CloudSurge 
user_description: Providing Devops Consultancy
user_title: Devops Consultancy 
email: info@cloudsurge.co.uk
github_username: cloudsurge 

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
